ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "utility_rebate_amount" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "federal_rebate_amount" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "rebate_request_notes" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "contractor_name" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "contractor_license_number" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "pre_approval_status" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "pre_approval_submitted_date" timestamp;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "pre_approval_approved_date" timestamp;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "pre_approval_notes" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "completion_notes" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "customer_attestation_signed" boolean DEFAULT false;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "customer_attestation_date" timestamp;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "contractor_attestation_signed" boolean DEFAULT false;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "contractor_attestation_date" timestamp;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "attestation_notes" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "reservation_number" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "payment_release_amount" text;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "case_closeout_date" timestamp;
ALTER TABLE "rebate_cases" ADD COLUMN IF NOT EXISTS "case_closeout_notes" text;
