import { useState, useMemo } from "react";
import { usePageTitle } from "@/hooks/use-page-title";
import { useLocation } from "wouter";
import { useQuery, useMutation } from "@tanstack/react-query";
import { getQueryFn, apiRequest, queryClient } from "@/lib/queryClient";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import {
  ChevronLeft,
  Plus,
  Pencil,
  Trash2,
  Loader2,
  GripVertical,
  Check,
  X,
  ExternalLink,
  BookOpen,
} from "lucide-react";
import { CrmLayout } from "@/components/crm/crm-layout";
import { useToast } from "@/hooks/use-toast";
import type { CrmUser, SalesbookBookmark, PricebookPackage, CrawlspaceTier } from "@shared/schema";
import {
  buildSalesbookSections,
  getSalesbookTOC,
  type EliteBundle,
  type EliteAirflowOption,
} from "@/components/salesbook-pages";

interface SalesbookData {
  staticPages: string[];
  pageWidth: number;
  pageHeight: number;
  packages: PricebookPackage[];
  crawlspaceTiers: CrawlspaceTier[];
  eliteCoreBundles: EliteBundle[];
  eliteAirflowOptions: EliteAirflowOption[];
}

export default function CrmSettingsSalesbook() {
  usePageTitle("Salesbook Directory");
  const [, navigate] = useLocation();
  const { toast } = useToast();

  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [deletingBookmark, setDeletingBookmark] = useState<SalesbookBookmark | null>(null);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editLabel, setEditLabel] = useState("");
  const [editPage, setEditPage] = useState("");
  const [newLabel, setNewLabel] = useState("");
  const [newPage, setNewPage] = useState("");
  const [showAddRow, setShowAddRow] = useState(false);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [localOrder, setLocalOrder] = useState<SalesbookBookmark[] | null>(null);

  const { data: currentUser, isLoading: authLoading } = useQuery<CrmUser | null>({
    queryKey: ["/api/crm/auth/me"],
    queryFn: getQueryFn({ on401: "returnNull" }),
  });

  const { data: bookmarks = [], isLoading: bookmarksLoading } = useQuery<SalesbookBookmark[]>({
    queryKey: ["/api/salesbook/bookmarks"],
  });

  const { data: salesbookData } = useQuery<SalesbookData>({
    queryKey: ["/api/salesbook/data"],
  });

  const autoGeneratedToc = useMemo(() => {
    if (!salesbookData) return [];
    const sections = buildSalesbookSections(
      salesbookData.staticPages,
      salesbookData.packages,
      salesbookData.crawlspaceTiers,
      salesbookData.eliteCoreBundles,
      salesbookData.eliteAirflowOptions,
    );
    return [{ label: "Introduction", page: 1 }, ...getSalesbookTOC(sections)];
  }, [salesbookData]);

  const createMutation = useMutation({
    mutationFn: async (data: { label: string; pageNumber: number; sortOrder: number }) => {
      const res = await apiRequest("POST", "/api/salesbook/bookmarks", data);
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/salesbook/bookmarks"] });
      setNewLabel("");
      setNewPage("");
      setShowAddRow(false);
      toast({ title: "Entry added" });
    },
    onError: () => toast({ title: "Failed to add entry", variant: "destructive" }),
  });

  const updateMutation = useMutation({
    mutationFn: async ({ id, ...data }: { id: string; label?: string; pageNumber?: number }) => {
      const res = await apiRequest("PATCH", `/api/salesbook/bookmarks/${id}`, data);
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/salesbook/bookmarks"] });
      setEditingId(null);
      toast({ title: "Entry updated" });
    },
    onError: () => toast({ title: "Failed to update", variant: "destructive" }),
  });

  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      await apiRequest("DELETE", `/api/salesbook/bookmarks/${id}`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/salesbook/bookmarks"] });
      setShowDeleteDialog(false);
      setDeletingBookmark(null);
      toast({ title: "Entry removed" });
    },
    onError: () => toast({ title: "Failed to delete", variant: "destructive" }),
  });

  const reorderMutation = useMutation({
    mutationFn: async (order: string[]) => {
      const res = await apiRequest("PUT", "/api/salesbook/bookmarks/reorder", { order });
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/salesbook/bookmarks"] });
    },
  });

  const displayBookmarks = localOrder ?? bookmarks;
  const autoEntries = autoGeneratedToc.map((t, i) => ({ id: `auto-${i}`, label: t.label, page: t.page, isCustom: false as const }));
  const customEntries = displayBookmarks.map((bm) => ({ id: bm.id, label: bm.label, page: bm.pageNumber, isCustom: true as const }));
  const activeEntries = [...autoEntries, ...customEntries];

  const handleDragStart = (index: number) => {
    setDraggedIndex(index);
    setLocalOrder([...bookmarks]);
  };

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    if (draggedIndex === null || draggedIndex === index || !localOrder) return;
    const reordered = [...localOrder];
    const [moved] = reordered.splice(draggedIndex, 1);
    reordered.splice(index, 0, moved);
    setLocalOrder(reordered);
    setDraggedIndex(index);
  };

  const handleDragEnd = () => {
    if (localOrder) {
      reorderMutation.mutate(localOrder.map((b) => b.id));
    }
    setDraggedIndex(null);
    setLocalOrder(null);
  };

  const startEdit = (bm: SalesbookBookmark) => {
    setEditingId(bm.id);
    setEditLabel(bm.label);
    setEditPage(String(bm.pageNumber));
  };

  const saveEdit = () => {
    if (!editingId) return;
    const pageNum = parseInt(editPage, 10);
    if (!editLabel.trim() || isNaN(pageNum) || pageNum < 1) {
      toast({ title: "Label and valid page number required", variant: "destructive" });
      return;
    }
    updateMutation.mutate({ id: editingId, label: editLabel.trim(), pageNumber: pageNum });
  };

  const handleAdd = () => {
    const pageNum = parseInt(newPage, 10);
    if (!newLabel.trim() || isNaN(pageNum) || pageNum < 1) {
      toast({ title: "Label and valid page number required", variant: "destructive" });
      return;
    }
    createMutation.mutate({
      label: newLabel.trim(),
      pageNumber: pageNum,
      sortOrder: bookmarks.length,
    });
  };

  if (authLoading) return null;
  if (!currentUser) {
    navigate("/crm/login");
    return null;
  }

  const isAdmin =
    currentUser.role === "owner" ||
    currentUser.role === "admin" ||
    currentUser.role === "supervisor";

  if (!isAdmin) {
    return (
      <CrmLayout currentUser={currentUser}>
        <div className="flex items-center justify-center py-20">
          <p className="text-slate-500">Only admins can manage the salesbook directory.</p>
        </div>
      </CrmLayout>
    );
  }

  return (
    <CrmLayout currentUser={currentUser}>
      <div className="space-y-4">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate("/crm/settings")}
          className="mb-4 text-slate-500 hover:text-slate-800 -ml-2"
        >
          <ChevronLeft className="h-4 w-4 mr-1" />
          Settings
        </Button>

        <div className="flex items-start justify-between mb-6">
          <div>
            <h1 className="text-xl font-bold text-slate-900">Salesbook Directory</h1>
            <p className="text-sm text-slate-500 mt-1">
              Manage the table of contents for the Sales Pricebook
            </p>
          </div>
          <div className="flex items-center gap-3">
            <a
              href="/price-book"
              target="_blank"
              rel="noopener noreferrer"
              className="text-sm text-slate-500 hover:text-[#711419] flex items-center gap-1.5"
            >
              <BookOpen className="h-4 w-4" />
              Open Salesbook
              <ExternalLink className="h-3 w-3" />
            </a>
          </div>
        </div>

        

        <div className="bg-white border border-slate-200 rounded-lg overflow-hidden">
          <div className="grid grid-cols-[40px_1fr_80px_72px] gap-0 bg-slate-50 border-b border-slate-200 px-4 py-2.5">
            <span />
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wider">Section</span>
            <span className="text-xs font-medium text-slate-500 uppercase tracking-wider text-center">Page</span>
            <span />
          </div>

          {bookmarksLoading ? (
            <div className="flex justify-center py-16">
              <Loader2 className="h-5 w-5 animate-spin text-slate-300" />
            </div>
          ) : (
            <div className="divide-y divide-slate-100">
              {activeEntries.map((entry, idx) => (
                <div
                  key={entry.id}
                  draggable={entry.isCustom && editingId !== entry.id}
                  onDragStart={() => entry.isCustom && handleDragStart(idx)}
                  onDragOver={(e) => entry.isCustom && handleDragOver(e, idx)}
                  onDragEnd={() => entry.isCustom && handleDragEnd()}
                  className={`grid grid-cols-[40px_1fr_80px_72px] gap-0 items-center px-4 transition-colors group ${
                    draggedIndex === idx ? "bg-slate-50" : "hover:bg-slate-50/60"
                  }`}
                >
                  {entry.isCustom ? (
                    <GripVertical className="h-4 w-4 text-slate-200 cursor-grab group-hover:text-slate-400 transition-colors" />
                  ) : (
                    <span className="text-xs text-slate-300 font-mono">{idx + 1}</span>
                  )}

                  {editingId === entry.id ? (
                    <>
                      <Input
                        value={editLabel}
                        onChange={(e) => setEditLabel(e.target.value)}
                        className="h-9 text-sm border-slate-200 my-1"
                        autoFocus
                        onKeyDown={(e) => {
                          if (e.key === "Enter") saveEdit();
                          if (e.key === "Escape") setEditingId(null);
                        }}
                      />
                      <Input
                        type="number"
                        min={1}
                        value={editPage}
                        onChange={(e) => setEditPage(e.target.value)}
                        className="h-9 text-sm text-center border-slate-200 mx-2"
                        onKeyDown={(e) => {
                          if (e.key === "Enter") saveEdit();
                          if (e.key === "Escape") setEditingId(null);
                        }}
                      />
                      <div className="flex items-center gap-1 justify-center">
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={saveEdit}
                          disabled={updateMutation.isPending}
                          className="h-7 w-7 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-50"
                        >
                          <Check className="h-3.5 w-3.5" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => setEditingId(null)}
                          className="h-7 w-7 text-slate-400 hover:text-slate-600"
                        >
                          <X className="h-3.5 w-3.5" />
                        </Button>
                      </div>
                    </>
                  ) : (
                    <>
                      <span className={`py-3 text-sm truncate ${entry.isCustom ? "text-slate-800" : "text-slate-500"}`}>
                        {entry.label}
                      </span>
                      <span className="text-sm text-slate-400 text-center tabular-nums">
                        {entry.page}
                      </span>
                      {entry.isCustom ? (
                        <div className="flex items-center gap-0.5 justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => {
                              const bm = bookmarks.find((b) => b.id === entry.id);
                              if (bm) startEdit(bm);
                            }}
                            className="h-7 w-7 text-slate-400 hover:text-slate-600"
                          >
                            <Pencil className="h-3.5 w-3.5" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => {
                              const bm = bookmarks.find((b) => b.id === entry.id);
                              if (bm) {
                                setDeletingBookmark(bm);
                                setShowDeleteDialog(true);
                              }
                            }}
                            className="h-7 w-7 text-slate-400 hover:text-red-500"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </Button>
                        </div>
                      ) : (
                        <span />
                      )}
                    </>
                  )}
                </div>
              ))}

              {showAddRow && (
                <div className="flex items-center gap-2 px-4 py-2 border-t border-dashed border-slate-200">
                  <Input
                    value={newLabel}
                    onChange={(e) => setNewLabel(e.target.value)}
                    placeholder="Section name"
                    className="h-8 text-sm border-slate-200 flex-1"
                    autoFocus
                    onKeyDown={(e) => {
                      if (e.key === "Enter") handleAdd();
                      if (e.key === "Escape") { setShowAddRow(false); setNewLabel(""); setNewPage(""); }
                    }}
                  />
                  <Input
                    type="number"
                    min={1}
                    value={newPage}
                    onChange={(e) => setNewPage(e.target.value)}
                    placeholder="Page"
                    className="h-8 w-16 text-sm text-center border-slate-200"
                    onKeyDown={(e) => {
                      if (e.key === "Enter") handleAdd();
                      if (e.key === "Escape") { setShowAddRow(false); setNewLabel(""); setNewPage(""); }
                    }}
                  />
                  <button
                    onClick={handleAdd}
                    disabled={createMutation.isPending}
                    className="text-slate-400 hover:text-emerald-600 transition-colors p-1"
                  >
                    {createMutation.isPending ? (
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    ) : (
                      <Check className="h-3.5 w-3.5" />
                    )}
                  </button>
                  <button
                    onClick={() => { setShowAddRow(false); setNewLabel(""); setNewPage(""); }}
                    className="text-slate-400 hover:text-slate-600 transition-colors p-1"
                  >
                    <X className="h-3.5 w-3.5" />
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        {!showAddRow && (
          <button
            onClick={() => setShowAddRow(true)}
            className="mt-3 flex items-center gap-1.5 text-xs text-slate-400 hover:text-slate-600 transition-colors"
          >
            <Plus className="h-3.5 w-3.5" />
            Add section
          </button>
        )}
      </div>

      <AlertDialog open={showDeleteDialog} onOpenChange={setShowDeleteDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Remove entry</AlertDialogTitle>
            <AlertDialogDescription>
              Remove "{deletingBookmark?.label}" from the directory?
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={() => deletingBookmark && deleteMutation.mutate(deletingBookmark.id)}
              className="bg-red-600 hover:bg-red-700"
            >
              {deleteMutation.isPending && <Loader2 className="h-4 w-4 mr-1 animate-spin" />}
              Remove
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </CrmLayout>
  );
}
