// Shared definitions for outbound marketing campaigns.
// The campaign wizard (client), the API routes, and the campaign engine all
// import from here so the audience/step/settings shapes stay in sync.
//
// Campaigns are audience-first outbound sequences (pick people → send a timed
// series of emails/texts), as opposed to automations (shared/automation.ts)
// which react to single CRM events. Reply detection is wired to the CRM's
// existing inbound stores: crm_messaging_messages (Textline SMS) and
// crm_email_messages (Gmail sync).

// ---------------------------------------------------------------------------
// Campaign lifecycle
// ---------------------------------------------------------------------------

export type CampaignStatus =
  | "draft" // being built in the wizard, nothing enrolled
  | "scheduled" // launched with a future start date
  | "active" // enrolled and sending
  | "paused" // enrollments frozen; resume picks up where it left off
  | "completed" // every enrollment reached a terminal state
  | "archived"; // cancelled — remaining enrollments stopped

export const CAMPAIGN_STATUS_LABELS: Record<CampaignStatus, string> = {
  draft: "Draft",
  scheduled: "Scheduled",
  active: "Active",
  paused: "Paused",
  completed: "Completed",
  archived: "Archived",
};

export type EnrollmentStatus =
  | "active" // waiting for its next step
  | "completed" // finished every step
  | "replied" // customer responded — sequence stopped (when stop-on-reply is on)
  | "stopped" // manually stopped / campaign cancelled
  | "skipped" // never sendable (no email & no phone for the chosen channels)
  | "failed"; // every remaining channel errored

// ---------------------------------------------------------------------------
// Sequence steps
// ---------------------------------------------------------------------------

export type CampaignStepType = "email" | "sms" | "task";

export type CampaignDelayUnit = "minutes" | "hours" | "days";

export type StepSendCondition = "always" | "no_reply";

export interface CampaignStep {
  /** Stable id generated by the wizard (used for per-step stats). */
  id: string;
  type: CampaignStepType;
  /** Wait before this step, measured from the previous step (or launch). */
  delay: number;
  delayUnit: CampaignDelayUnit;
  /** "no_reply" skips the step when the customer has already responded. */
  onlyIf: StepSendCondition;
  /** Email subject. */
  subject?: string;
  /** Email body / SMS text / internal task note. Supports merge fields. */
  body?: string;
  /** Internal task title (task steps only). */
  title?: string;
}

export const CAMPAIGN_DELAY_UNITS: { value: CampaignDelayUnit; label: string }[] = [
  { value: "minutes", label: "minutes" },
  { value: "hours", label: "hours" },
  { value: "days", label: "days" },
];

export const CAMPAIGN_DELAY_MS: Record<CampaignDelayUnit, number> = {
  minutes: 60_000,
  hours: 3_600_000,
  days: 86_400_000,
};

export const MAX_CAMPAIGN_STEPS = 10;

/** Merge fields supported by the campaign engine (same family as automations). */
export const CAMPAIGN_MERGE_FIELDS: { token: string; label: string }[] = [
  { token: "{firstName}", label: "First name" },
  { token: "{name}", label: "Full name" },
];

export function describeStepDelay(step: Pick<CampaignStep, "delay" | "delayUnit">): string {
  if (!step.delay) return "Immediately";
  const unit = step.delay === 1 ? step.delayUnit.replace(/s$/, "") : step.delayUnit;
  return `Wait ${step.delay} ${unit}`;
}

// ---------------------------------------------------------------------------
// Audience
// ---------------------------------------------------------------------------

export interface AudienceFilters {
  /** [] = any. Values from crm_customers.customer_type. */
  customerType: string[];
  /** [] = any. "prospect" | "customer". */
  customerStatus: string[];
  /** Any-of match against crm_customers.tags. */
  tags: string[];
  /** Any-of match against crm_properties.city. */
  cities: string[];
  /** Any-of match against crm_properties.zip. */
  zips: string[];
  /** Any-of match against crm_customers.lead_source. */
  leadSources: string[];
  hasAgreement: "any" | "yes" | "no";
  protectionPlan: "any" | "yes" | "no";
  /** Completed work order within the last N days. */
  lastJobWithinDays: number | null;
  /** No completed work order within the last N days (win-back). */
  lastJobOlderThanDays: number | null;
  /** Lifetime paid invoice total ≥ N dollars. */
  minLifetimeRevenue: number | null;
}

export interface AudienceSegment {
  id: string;
  name: string;
  filters: AudienceFilters;
}

export interface CampaignAudience {
  /** Segments are unioned, then de-duplicated by customer. */
  segments: AudienceSegment[];
  /** Manual removals from the audience preview. */
  excludeCustomerIds: string[];
  /** Skip anyone another campaign contacted within N days. 0 = off. */
  excludeContactedWithinDays: number;
}

export function emptyFilters(): AudienceFilters {
  return {
    customerType: [],
    customerStatus: [],
    tags: [],
    cities: [],
    zips: [],
    leadSources: [],
    hasAgreement: "any",
    protectionPlan: "any",
    lastJobWithinDays: null,
    lastJobOlderThanDays: null,
    minLifetimeRevenue: null,
  };
}

export function defaultAudience(): CampaignAudience {
  return {
    segments: [{ id: "seg-1", name: "Segment 1", filters: emptyFilters() }],
    excludeCustomerIds: [],
    excludeContactedWithinDays: 30,
  };
}

/** Human summary chips for a segment's filters (used by wizard + detail page). */
export function describeFilters(f: AudienceFilters): string[] {
  const parts: string[] = [];
  if (f.customerStatus.length) parts.push(f.customerStatus.map((s) => (s === "prospect" ? "Leads" : "Customers")).join(" or "));
  if (f.customerType.length) parts.push(f.customerType.map((t) => t.replace(/_/g, " ")).join(" or "));
  if (f.tags.length) parts.push(`Tagged: ${f.tags.join(", ")}`);
  if (f.cities.length) parts.push(`In ${f.cities.join(", ")}`);
  if (f.zips.length) parts.push(`ZIP ${f.zips.join(", ")}`);
  if (f.leadSources.length) parts.push(`Source: ${f.leadSources.join(", ")}`);
  if (f.hasAgreement === "yes") parts.push("Has agreement");
  if (f.hasAgreement === "no") parts.push("No agreement");
  if (f.protectionPlan === "yes") parts.push("On protection plan");
  if (f.protectionPlan === "no") parts.push("No protection plan");
  if (f.lastJobWithinDays) parts.push(`Job in last ${f.lastJobWithinDays}d`);
  if (f.lastJobOlderThanDays) parts.push(`No job in ${f.lastJobOlderThanDays}d`);
  if (f.minLifetimeRevenue) parts.push(`Revenue ≥ $${f.minLifetimeRevenue.toLocaleString()}`);
  return parts.length ? parts : ["Everyone"];
}

// ---------------------------------------------------------------------------
// Settings (reply behavior + schedule + safeguards)
// ---------------------------------------------------------------------------

export interface CampaignReplyBehavior {
  /** Stop remaining steps when the customer replies (email or text). */
  stopSequence: boolean;
  /** Post an in-app notification to the team when someone replies. */
  notifyTeam: boolean;
  /** Create a CRM follow-up on the customer when someone replies. */
  createFollowUp: boolean;
}

export interface CampaignSchedule {
  startMode: "now" | "scheduled";
  /** ISO timestamp when startMode = "scheduled". */
  startAt: string | null;
  /** Hold sends between 9pm and 8am. */
  quietHours: boolean;
  /** Max sends per day for this campaign. 0 = unlimited. */
  dailySendCap: number;
}

export interface CampaignSettings {
  reply: CampaignReplyBehavior;
  schedule: CampaignSchedule;
}

export function defaultCampaignSettings(): CampaignSettings {
  return {
    reply: { stopSequence: true, notifyTeam: true, createFollowUp: false },
    schedule: { startMode: "now", startAt: null, quietHours: true, dailySendCap: 0 },
  };
}

/** Which contact fields the sequence needs, based on its steps. */
export function campaignChannelNeeds(steps: CampaignStep[]): { needsEmail: boolean; needsPhone: boolean } {
  return {
    needsEmail: steps.some((s) => s.type === "email"),
    needsPhone: steps.some((s) => s.type === "sms"),
  };
}

// ---------------------------------------------------------------------------
// Template gallery
// ---------------------------------------------------------------------------

export interface CampaignTemplate {
  key: string;
  name: string;
  tagline: string;
  /** lucide-react icon name (client resolves it). */
  icon: string;
  accent: string;
  suggestedFilters: Partial<AudienceFilters>;
  steps: Omit<CampaignStep, "id">[];
  reply?: Partial<CampaignReplyBehavior>;
}

export const CAMPAIGN_TEMPLATES: CampaignTemplate[] = [
  {
    key: "seasonal_tuneup",
    name: "Seasonal Tune-Up Push",
    tagline: "Fill the shoulder-season schedule before the rush.",
    icon: "Sun",
    accent: "#d97706",
    suggestedFilters: { customerStatus: ["customer"], hasAgreement: "no" },
    steps: [
      {
        type: "email",
        delay: 0,
        delayUnit: "days",
        onlyIf: "always",
        subject: "{firstName}, beat the rush — book your seasonal tune-up",
        body: "Hi {firstName},\n\nExtreme temps are right around the corner, and our schedule fills up fast once they hit. A seasonal tune-up now keeps your system efficient and catches small issues before they become emergency calls.\n\nReply to this email or give us a call and we'll find a time that works for you.\n\n— The GHVAC Team",
      },
      {
        type: "sms",
        delay: 2,
        delayUnit: "days",
        onlyIf: "no_reply",
        body: "Hi {firstName}, it's GHVAC — tune-up slots for this season are filling up. Want us to hold one for you? Just text back and we'll get you scheduled.",
      },
      {
        type: "email",
        delay: 4,
        delayUnit: "days",
        onlyIf: "no_reply",
        subject: "Last call for priority tune-up scheduling",
        body: "Hi {firstName},\n\nJust a final nudge — we're holding a few priority tune-up slots for existing customers this week. After that, scheduling moves out several weeks.\n\nReply here and we'll take care of the rest.\n\n— The GHVAC Team",
      },
    ],
  },
  {
    key: "winback",
    name: "Win Back Lapsed Customers",
    tagline: "Re-engage customers you haven't serviced in a year.",
    icon: "RotateCcw",
    accent: "#0ea5e9",
    suggestedFilters: { customerStatus: ["customer"], lastJobOlderThanDays: 365 },
    steps: [
      {
        type: "email",
        delay: 0,
        delayUnit: "days",
        onlyIf: "always",
        subject: "It's been a while, {firstName} — how's your system running?",
        body: "Hi {firstName},\n\nIt's been over a year since we last serviced your system, and annual maintenance is the single best way to avoid surprise breakdowns and keep efficiency up.\n\nAs a returning customer, we'd love to get you back on the calendar — reply here and we'll set it up.\n\n— The GHVAC Team",
      },
      {
        type: "sms",
        delay: 3,
        delayUnit: "days",
        onlyIf: "no_reply",
        body: "Hi {firstName}, GHVAC here. It's been a while since your last service — want us to get you on the schedule for a check-up? Text back and we'll handle it.",
      },
      {
        type: "task",
        delay: 4,
        delayUnit: "days",
        onlyIf: "no_reply",
        title: "Call win-back campaign contact",
        body: "No response to the win-back email or text — worth a personal call.",
      },
    ],
  },
  {
    key: "protection_upsell",
    name: "Protection Plan Upsell",
    tagline: "Turn recent service customers into plan members.",
    icon: "ShieldCheck",
    accent: "#16a34a",
    suggestedFilters: { customerStatus: ["customer"], protectionPlan: "no", lastJobWithinDays: 90 },
    steps: [
      {
        type: "email",
        delay: 0,
        delayUnit: "days",
        onlyIf: "always",
        subject: "{firstName}, protect the work we just did",
        body: "Hi {firstName},\n\nThanks again for having us out recently. The best way to protect that investment is a GHVAC protection plan: seasonal tune-ups, priority scheduling, and discounts on repairs — all covered.\n\nReply to this email and we'll walk you through the options in two minutes.\n\n— The GHVAC Team",
      },
      {
        type: "sms",
        delay: 3,
        delayUnit: "days",
        onlyIf: "no_reply",
        body: "Hi {firstName}, it's GHVAC — quick follow-up: our protection plans cover seasonal tune-ups and get you priority scheduling. Want the details? Just text back.",
      },
    ],
  },
  {
    key: "review_blast",
    name: "Review Request Blast",
    tagline: "Ask recent customers for a Google review.",
    icon: "Star",
    accent: "#7c3aed",
    suggestedFilters: { customerStatus: ["customer"], lastJobWithinDays: 30 },
    steps: [
      {
        type: "sms",
        delay: 0,
        delayUnit: "days",
        onlyIf: "always",
        body: "Hi {firstName}! Thanks for choosing GHVAC. If we did a great job, a quick Google review means the world to our small team. Reply here if anything wasn't perfect and we'll make it right.",
      },
      {
        type: "sms",
        delay: 4,
        delayUnit: "days",
        onlyIf: "no_reply",
        body: "Hi {firstName}, one small favor — a 30-second Google review helps neighbors find us. Thanks so much! — GHVAC",
      },
    ],
  },
  {
    key: "referral",
    name: "Referral Ask",
    tagline: "Ask your happiest customers to spread the word.",
    icon: "Gift",
    accent: "#db2777",
    suggestedFilters: { customerStatus: ["customer"], hasAgreement: "yes" },
    steps: [
      {
        type: "email",
        delay: 0,
        delayUnit: "days",
        onlyIf: "always",
        subject: "Know someone who needs a good HVAC company?",
        body: "Hi {firstName},\n\nMost of our best customers come from referrals — people like you telling a neighbor or friend about us.\n\nIf you know someone who could use honest, quality HVAC work, just reply with their name and number (or forward this along) and we'll take great care of them.\n\nThanks for being one of our favorite customers.\n\n— The GHVAC Team",
      },
      {
        type: "sms",
        delay: 5,
        delayUnit: "days",
        onlyIf: "no_reply",
        body: "Hi {firstName}! Quick one from GHVAC — if you know anyone who needs heating or cooling help, send them our way and we'll treat them right. Thanks for the trust!",
      },
    ],
  },
  {
    key: "announcement",
    name: "Promotion or Announcement",
    tagline: "One-time blast: a promo, new service, or news.",
    icon: "Megaphone",
    accent: "#711419",
    suggestedFilters: {},
    steps: [
      {
        type: "email",
        delay: 0,
        delayUnit: "days",
        onlyIf: "always",
        subject: "Some news from GHVAC",
        body: "Hi {firstName},\n\n[Write your announcement here — what's new, what it means for the customer, and what they should do next.]\n\nReply to this email with any questions.\n\n— The GHVAC Team",
      },
      {
        type: "sms",
        delay: 2,
        delayUnit: "days",
        onlyIf: "no_reply",
        body: "Hi {firstName}, GHVAC here — [one-line version of your announcement]. Text back with any questions!",
      },
    ],
  },
  {
    key: "scratch",
    name: "Start from Scratch",
    tagline: "A blank canvas — build your own sequence.",
    icon: "PenLine",
    accent: "#64748b",
    suggestedFilters: {},
    steps: [],
  },
];

export function campaignTemplate(key: string | null | undefined): CampaignTemplate | undefined {
  return CAMPAIGN_TEMPLATES.find((t) => t.key === key);
}
