/*
  GHVAC Email Service – Gmail-compatible transactional templates (Mobile-optimized, V4)
  ------------------------------------------------------------------
  Drop-in replacement.
  - Header refined: logo LEFT, "New HVAC Quote" beside it (horizontally aligned)
  - "Generated by <tech>" centered BELOW header row
  - Status pill stays on right of header row
  - Parts: table on desktop, card layout on mobile
  - Removed top Total; Total shown in Quote Summary only
  - No API/behavior changes
*/

import { Resend } from "resend";

// -----------------------------
// Types (unchanged)
// -----------------------------
export interface EmailConfig {
  serviceProvider: "resend" | "generic";
  apiKey: string;
  fromEmail: string;
  managerEmail: string;
  brandName?: string;
  brandColor?: string;
  logoUrl?: string;
  bccManagerByDefault?: boolean;
  dryRun?: boolean;
}

export interface QuoteEmailData {
  customerName: string;
  technician: string;
  total: string | number;
  quoteText?: string;
  quoteId: string;
  jobNotes?: string;
  parts: Array<{
    id: string;
    partNumber: string;
    description: string;
    price: string | number;
    quantity?: number;
  }>;
  subtotal: string | number;
  labor: string | number;
  tax: string | number;
  status?: "draft" | "pending" | "approved" | "revised" | string;
  createdAt?: string | Date;
}

// -----------------------------
// Utilities (unchanged behavior)
// -----------------------------
const brandDefaults = {
  name: "Giesbrecht HVAC",
  color: "#711419",
};

function asCurrency(v: string | number, locale = "en-US", currency = "USD") {
  const n =
    typeof v === "string" ? Number(v.replace(/[^0-9.-]/g, "")) : Number(v);
  if (Number.isNaN(n)) return String(v);
  return new Intl.NumberFormat(locale, { style: "currency", currency }).format(
    n,
  );
}

function formatDate(d?: string | Date) {
  const date = d ? new Date(d) : new Date();
  try {
    return new Intl.DateTimeFormat("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      hour12: true,
    }).format(date);
  } catch {
    return date.toDateString();
  }
}

function esc(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\\"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function statusPillColor(status?: string, brandColor = brandDefaults.color) {
  const s = (status || "draft").toLowerCase();
  const map: Record<string, { bg: string; fg: string }> = {
    draft: { bg: "#F3F4F6", fg: "#374151" },
    pending: { bg: "#FEF3C7", fg: "#92400E" },
    approved: { bg: "#ECFDF5", fg: "#065F46" },
    revised: { bg: "#E0E7FF", fg: "#3730A3" },
  };
  return map[s] || { bg: brandColor + "22", fg: brandColor };
}

// -----------------------------
// Template Builder (V4 header refinement)
// -----------------------------
export class QuoteEmailTemplate {
  constructor(private cfg: EmailConfig) {}

  subject(data: QuoteEmailData) {
    return `New HVAC Quote – ${data.customerName} – ${asCurrency(data.total)}`;
  }

  preheader(data: QuoteEmailData) {
    const partsCount = data.parts?.length || 0;
    return `${data.technician} created quote ${data.quoteId} • ${partsCount} item${partsCount === 1 ? "" : "s"} • Total ${asCurrency(data.total)}`;
  }

  textBody(data: QuoteEmailData) {
    const lines: string[] = [];
    const brand = this.cfg.brandName || brandDefaults.name;
    lines.push(`${brand} – Quote ${data.quoteId}`);
    lines.push(`Customer: ${data.customerName}`);
    lines.push(`Technician: ${data.technician}`);
    lines.push(`Status: ${data.status || "draft"}`);
    lines.push(`Created: ${formatDate(data.createdAt)}`);
    lines.push("");
    lines.push("Items:");
    if (data.parts?.length) {
      data.parts.forEach((p) => {
        lines.push(
          `- ${p.description} (Part #${p.partNumber}) x${p.quantity ?? 1} – ${asCurrency(p.price)}`,
        );
      });
    } else {
      lines.push("- No parts listed");
    }
    lines.push("");
    lines.push(`Subtotal: ${asCurrency(data.subtotal)}`);
    lines.push(`Labor:    ${asCurrency(data.labor)}`);
    lines.push(`Tax:      ${asCurrency(data.tax)}`);
    lines.push(`Total:    ${asCurrency(data.total)}`);
    if (data.jobNotes) {
      lines.push("", "Job Notes:", data.jobNotes);
    }
    if (data.quoteText) {
      lines.push("", "Summary:", data.quoteText);
    }
    lines.push("", "This is a transactional message.");
    return lines.join("\n");
  }

  htmlBody(data: QuoteEmailData) {
    const brandName = this.cfg.brandName || brandDefaults.name;
    const brandColor = this.cfg.brandColor || brandDefaults.color;
    const pill = statusPillColor(data.status, brandColor);
    const preheader = esc(this.preheader(data));

    const partsRows = (data.parts || [])
      .map(
        (p) => `
      <tr role="row" class="row">
        <td class="cell cell-desc" role="cell" style="padding:14px 14px 8px;border-bottom:1px solid #e5e7eb;font-family:Arial,sans-serif;">
          <div style="font-weight:700;color:#111827;margin-bottom:4px;">${esc(p.description)}</div>
          <div style="font-size:12px;color:#6b7280;">Part #: ${esc(p.partNumber)}</div>
        </td>
        <td class="cell cell-qty" role="cell" style="padding:14px 10px 8px;text-align:center;border-bottom:1px solid #e5e7eb;color:#6b7280;font-family:Arial,sans-serif;white-space:nowrap;">Qty: ${p.quantity ?? 1}</td>
        <td class="cell cell-price" role="cell" style="padding:14px 14px 8px;text-align:right;border-bottom:1px solid #e5e7eb;color:#111827;font-weight:800;font-family:Arial,sans-serif;white-space:nowrap;">${esc(asCurrency(p.price))}</td>
      </tr>`,
      )
      .join("");

    const logoImg = this.cfg.logoUrl
      ? `<img src="${esc(this.cfg.logoUrl)}" alt="${esc(brandName)}" width="100" style="height:auto;border:0;display:block;"/>`
      : `<div style="font-size:18px;font-weight:700;color:white;">${esc(brandName)}</div>`;

    const maybeJobNotes = data.jobNotes
      ? `
      <tr>
        <td style="padding:0 20px 18px 20px;">
          <div style="background:#fff7ed;border:1px solid #fed7aa;padding:12px 14px;border-radius:10px;">
            <div style="font-weight:800;color:#9a3412;font-family:Arial,sans-serif;">Job Notes</div>
            <div style="margin-top:6px;color:#7c2d12;font-family:Arial,sans-serif;line-height:1.55;">${esc(data.jobNotes)}</div>
          </div>
        </td>
      </tr>`
      : "";

    const noPartsRow =
      partsRows ||
      `<tr><td colspan="3" style="padding:18px;text-align:center;color:#6b7280;font-style:italic;font-family:Arial,sans-serif;">No parts listed</td></tr>`;

    // Inline CSS + media query for card layout on phones
    const headCss = `
      :root { color-scheme: light only; supported-color-schemes: light; }
      body { margin:0; padding:0; }
      table { border-collapse:collapse; }
      img { border:0; line-height:100%; text-decoration:none; }
      .container { width:100% !important; max-width:600px !important; }
      .px-24 { padding-left:20px; padding-right:20px; }
      .py-24 { padding-top:18px; padding-bottom:18px; }
      .stack { display:table; width:100%; }
      .stack .col { display:table-cell; vertical-align:middle; }
      .table { width:100%; background:#f9fafb; border-radius:12px; overflow:hidden; }
      .thead { background:#f3f4f6; }
      .pill { display:inline-block; padding:6px 10px; border-radius:999px; font-weight:800; font-size:12px; }

      /* Mobile */
      @media only screen and (max-width: 600px) {
        .container { width:100% !important; max-width:100% !important; border-radius:0 !important; }
        .px-24 { padding-left:14px !important; padding-right:14px !important; }
        .py-24 { padding-top:14px !important; padding-bottom:14px !important; }
        .stack .col, .stack-column { display:block !important; width:100% !important; text-align:center !important; }

        /* Card layout for parts */
        table.table.table-cards thead { display:none !important; }
        table.table.table-cards tbody tr.row { display:block !important; background:#ffffff; margin:0 0 12px 0; border-radius:12px; box-shadow:0 1px 2px rgba(0,0,0,0.08); }
        table.table.table-cards tbody tr.row td { display:block !important; text-align:left !important; border-bottom:0 !important; padding:12px 14px !important; }
        table.table.table-cards tbody tr.row td.cell-qty { color:#6b7280 !important; margin-top:2px !important; }
        table.table.table-cards tbody tr.row td.cell-price { margin-top:6px !important; font-weight:900 !important; }
      }
    `;

    return `<!doctype html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="x-apple-disable-message-reformatting" />
  <title>${esc(this.subject(data))}</title>
  <style type="text/css">${headCss}</style>
</head>
<body style="margin:0;padding:0;font-family:Arial,Segoe UI,Roboto,Helvetica,sans-serif;background-color:#f3f4f6;">
  <div style="display:none;font-size:1px;color:#fefefe;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;">${preheader}</div>

  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f3f4f6;">
    <tr>
      <td align="center" style="padding:16px 0;">
        <table role="presentation" cellpadding="0" cellspacing="0" class="container" style="background-color:#ffffff;border-radius:14px;overflow:hidden;box-shadow:0 2px 8px rgba(16,24,40,0.08);">

          <!-- Header: logo LEFT, title moved right, status pill far right - all vertically centered -->
          <tr>
            <td style="background:${brandColor};padding:16px 20px;color:#ffffff;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td style="width:100px;vertical-align:middle;padding-right:16px;">
                    ${logoImg}
                  </td>
                  <td style="vertical-align:middle;text-align:center;padding:0 20px;">
                    <div style="font-size:18px;font-weight:900;letter-spacing:0.2px;line-height:1.2;color:#fff;">
                      New HVAC Quote
                    </div>
                  </td>
                  <td style="text-align:right;vertical-align:middle;white-space:nowrap;width:120px;">
                    <span class="pill" style="background:${pill.bg};color:${pill.fg};">${esc((data.status || "draft").toUpperCase())}</span>
                  </td>
                </tr>
              </table>
              <div style="margin-top:8px;text-align:center;font-size:13px;color:rgba(255,255,255,0.92);">
                Generated by ${esc(data.technician)}
              </div>
            </td>
          </tr>

          <!-- Customer / Meta (no top Total) -->
          <tr>
            <td class="px-24 py-24">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                <tr class="stack">
                  <td class="col stack-column" style="vertical-align:top;">
                    <div style="font-size:12px;color:#6b7280;">Customer</div>
                    <h2 style="margin:2px 0 6px 0;font-size:20px;color:#111827;font-weight:900;">${esc(data.customerName)}</h2>
                    <div style="font-size:12px;color:#6b7280;">Quote ID: ${esc(data.quoteId)}</div>
                  </td>
                  <td class="col stack-column" style="vertical-align:top;text-align:right;">
                    <div style="color:#6b7280;font-size:12px;">${data.parts?.length || 0} item${(data.parts?.length || 0) !== 1 ? "s" : ""}</div>
                    <div style="margin-top:4px;color:#6b7280;font-size:12px;">${formatDate(data.createdAt)}</div>
                  </td>
                </tr>
              </table>
              <div style="border-bottom:1px solid #e5e7eb;margin-top:12px;"></div>
            </td>
          </tr>

          ${maybeJobNotes}

          <!-- Parts & Services (table desktop / cards mobile) -->
          <tr>
            <td class="px-24" style="padding-bottom:18px;">
              <h3 style="margin:0 0 10px 0;font-size:16px;color:#111827;font-weight:900;">Parts & Services</h3>
              <table role="table" width="100%" cellpadding="0" cellspacing="0" class="table table-cards" style="background:#f9fafb;border-radius:12px;overflow:hidden;">
                <thead class="thead">
                  <tr>
                    <th scope="col" style="padding:12px;text-align:left;font-weight:900;color:#374151;">Description</th>
                    <th scope="col" style="padding:12px;text-align:center;font-weight:900;color:#374151;">Qty</th>
                    <th scope="col" style="padding:12px;text-align:right;font-weight:900;color:#374151;">Price</th>
                  </tr>
                </thead>
                <tbody>${noPartsRow}</tbody>
              </table>
            </td>
          </tr>

          <!-- Quote Summary (Total only here) -->
          <tr>
            <td class="px-24" style="padding-bottom:20px;">
              <h3 style="margin:0 0 10px 0;font-size:16px;color:#111827;font-weight:900;">Quote Summary</h3>
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f9fafb;border-radius:12px;padding:12px 14px;">
                <tr>
                  <td style="padding:8px 0;color:#374151;">Parts Subtotal</td>
                  <td style="padding:8px 0;text-align:right;color:#374151;">${esc(asCurrency(data.subtotal))}</td>
                </tr>
                <tr style="border-bottom:1px solid #e5e7eb;">
                  <td style="padding:8px 0;color:#374151;">Labor</td>
                  <td style="padding:8px 0;text-align:right;color:#374151;">${esc(asCurrency(data.labor))}</td>
                </tr>
                <tr style="border-bottom:1px solid #e5e7eb;">
                  <td style="padding:8px 0;color:#374151;">Tax</td>
                  <td style="padding:8px 0;text-align:right;color:#374151;">${esc(asCurrency(data.tax))}</td>
                </tr>
                <tr style="border-top:1px solid #e5e7eb;">
                  <td style="padding:12px 0 4px 0;font-weight:900;font-size:15px;color:${brandColor};">Total</td>
                  <td style="padding:12px 0 4px 0;text-align:right;font-weight:900;font-size:18px;color:${brandColor};">${esc(asCurrency(data.total))}</td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#f3f4f6;padding:14px 18px;text-align:center;color:#6b7280;">
              <p style="margin:0;font-weight:900;color:#111827;">${esc(brandName)}</p>
              <p style="margin:6px 0 0 0;font-size:12px;">Professional Service Solutions</p>
              <p style="margin:8px 0 0 0;font-size:12px;">This is a transactional message.</p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>

</body>
</html>`;
  }
}

// -----------------------------
// Email Service (unchanged)
// -----------------------------
export class EmailService {
  private cfg: EmailConfig;
  private resend: Resend;
  private builder: QuoteEmailTemplate;

  constructor() {
    this.cfg = {
      serviceProvider:
        (process.env.EMAIL_SERVICE as EmailConfig["serviceProvider"]) ||
        "resend",
      apiKey: process.env.RESEND_API_KEY || "",
      fromEmail: process.env.FROM_EMAIL || "quotes@ghvac.work",
      managerEmail: process.env.MANAGER_EMAIL || "manager@ghvac.com",
      brandName: process.env.BRAND_NAME || "Giesbrecht HVAC",
      brandColor: process.env.BRAND_COLOR || "#711419",
      logoUrl:
        "https://images.squarespace-cdn.com/content/v1/65b2790c0b83175df7337294/93a31506-d2ae-4e07-958b-c86d0c49f7cd/GHVAC-icons.png?format=200w",
      bccManagerByDefault:
        (process.env.BCC_MANAGER_BY_DEFAULT || "true") === "true",
      dryRun: (process.env.DRY_RUN_EMAIL || "false") === "true",
    };

    this.resend = new Resend(this.cfg.apiKey);
    this.builder = new QuoteEmailTemplate(this.cfg);
  }

  async sendQuoteNotification(
    quoteData: QuoteEmailData,
    recipients?: string[],
  ): Promise<boolean> {
    try {
      const subject = this.builder.subject(quoteData);
      const html = this.builder.htmlBody(quoteData);
      const text = this.builder.textBody(quoteData);
      const to = recipients?.length ? recipients : [this.cfg.managerEmail];

      if (this.cfg.dryRun) {
        console.log("[DRY RUN] Would send email", {
          subject,
          to,
          bcc: this.cfg.bccManagerByDefault ? this.cfg.managerEmail : undefined,
        });
        return true;
      }

      if (this.cfg.serviceProvider === "resend") {
        return await this.sendWithResend({ subject, html, text, to });
      } else {
        return await this.sendWithGeneric({ subject, html, text, to });
      }
    } catch (err) {
      console.error("Error sending quote notification:", err);
      return false;
    }
  }

  private async sendWithResend({
    subject,
    html,
    text,
    to,
  }: {
    subject: string;
    html: string;
    text: string;
    to: string[];
  }): Promise<boolean> {
    try {
      const payload: Parameters<typeof this.resend.emails.send>[0] = {
        from: this.cfg.fromEmail,
        to,
        subject,
        html,
        text,
        bcc: this.cfg.bccManagerByDefault ? [this.cfg.managerEmail] : undefined,
        headers: { "X-Entity-Ref-ID": `quote-${Date.now()}` },
      };

      const { data, error } = await this.resend.emails.send(payload);

      if (error) {
        console.error("Resend error:", error);

        // Optional fallback pattern (keep if you use a custom domain that sometimes fails validation)
        // if ((error as any).name === "validation_error" && /@ghvac\.work$/i.test(this.cfg.fromEmail)) {
        //   const { data: data2, error: error2 } = await this.resend.emails.send({
        //     ...payload,
        //     from: "delivered@resend.dev",
        //     subject: subject + " [Fallback]",
        //   });
        //   if (error2) { console.error("Fallback send also failed:", error2); return false; }
        //   console.log("Email sent via fallback:", data2?.id);
        //   return true;
        // }

        return false;
      }

      console.log("Email sent successfully:", data?.id);
      return true;
    } catch (err) {
      console.error("Resend transport error:", err);
      return false;
    }
  }

  private async sendWithGeneric({
    subject,
    html,
    text,
    to,
  }: {
    subject: string;
    html: string;
    text: string;
    to: string[];
  }): Promise<boolean> {
    console.log("[GENERIC EMAIL] Would send:", {
      subject,
      to,
      textPreview: text.slice(0, 140) + "…",
    });
    return true;
  }
}

export const emailService = new EmailService();+
