import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft, Download, Trash2, Edit } from "lucide-react";
import type { Process } from "@shared/schema";
import { jsPDF } from "jspdf";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import ProcessEditForm from "./process-edit-form";
import { queryClient } from "@/lib/queryClient";

interface ProcessDetailViewProps {
  process: Process;
  onBack: () => void;
  onDelete: (id: string) => void;
}

export default function ProcessDetailView({ process, onBack, onDelete }: ProcessDetailViewProps) {
  const [isEditing, setIsEditing] = useState(false);

  const handleEditSuccess = () => {
    setIsEditing(false);
    queryClient.invalidateQueries({ queryKey: ['/api/processes'] });
  };

  if (isEditing) {
    return (
      <ProcessEditForm
        process={process}
        onSuccess={handleEditSuccess}
        onCancel={() => setIsEditing(false)}
      />
    );
  }
  const exportToPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - (margin * 2);
    let yPosition = 20;

    // Title
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text(process.name, margin, yPosition);
    yPosition += 15;

    // Category
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text(`Category: ${process.category}`, margin, yPosition);
    yPosition += 10;

    // Description
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text("Description:", margin, yPosition);
    yPosition += 7;
    
    doc.setFont("helvetica", "normal");
    const descriptionLines = doc.splitTextToSize(process.description, maxWidth);
    doc.text(descriptionLines, margin, yPosition);
    yPosition += (descriptionLines.length * 7) + 15;

    // Steps
    doc.setFont("helvetica", "bold");
    doc.text("Step-by-Step Instructions:", margin, yPosition);
    yPosition += 10;

    doc.setFont("helvetica", "normal");
    process.steps?.forEach((step, index) => {
      // Check if we need a new page
      if (yPosition > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
        yPosition = 20;
      }

      doc.setFont("helvetica", "bold");
      doc.text(`Step ${step.stepNumber}:`, margin, yPosition);
      doc.setFont("helvetica", "normal");
      
      const stepLines = doc.splitTextToSize(step.instruction, maxWidth - 20);
      doc.text(stepLines, margin + 20, yPosition);
      yPosition += (stepLines.length * 7) + 8;
    });

    // Add footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by GHVAC Processes & Systems - Page ${i} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    }

    doc.save(`${process.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_process.pdf`);
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <Button variant="ghost" onClick={onBack} data-testid="button-back" className="flex-shrink-0">
          <ArrowLeft className="h-4 w-4 mr-2" />
          Back to Wiki
        </Button>
        <div className="flex flex-wrap gap-2 w-full sm:w-auto">
          <Button onClick={() => setIsEditing(true)} variant="outline" data-testid="button-edit-process" className="flex-1 sm:flex-none">
            <Edit className="h-4 w-4 mr-2" />
            <span className="hidden sm:inline">Edit</span>
          </Button>
          <Button onClick={exportToPDF} variant="outline" data-testid="button-export-pdf" className="flex-1 sm:flex-none">
            <Download className="h-4 w-4 mr-2" />
            <span className="hidden sm:inline">Export PDF</span>
          </Button>
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="destructive" data-testid="button-delete" className="flex-1 sm:flex-none">
                <Trash2 className="h-4 w-4 mr-2" />
                <span className="hidden sm:inline">Delete</span>
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Delete Process</AlertDialogTitle>
                <AlertDialogDescription>
                  Are you sure you want to delete "{process.name}"? This action cannot be undone.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={() => onDelete(process.id)} data-testid="button-confirm-delete">
                  Delete
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      </div>

      <Card className="break-words">
        <CardHeader>
          <div className="flex items-start justify-between">
            <div className="flex-1 min-w-0">
              <CardTitle className="text-xl sm:text-2xl break-words" data-testid="text-process-title">{process.name}</CardTitle>
              <div className="mt-2">
                <span className="text-sm bg-primary/10 text-primary px-3 py-1 rounded" data-testid="text-process-category">
                  {process.category}
                </span>
              </div>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          <div>
            <h3 className="font-semibold text-lg mb-2">Description</h3>
            <p className="text-muted-foreground break-words" data-testid="text-process-description">{process.description}</p>
          </div>

          <div>
            <h3 className="font-semibold text-lg mb-3">Step-by-Step Instructions</h3>
            <div className="space-y-4">
              {process.steps?.map((step) => (
                <div key={step.id} className="flex gap-3 sm:gap-4" data-testid={`step-display-${step.id}`}>
                  <div className="flex-shrink-0 w-8 h-8 rounded-full bg-primary/10 text-primary flex items-center justify-center font-semibold">
                    {step.stepNumber}
                  </div>
                  <div className="flex-1 pt-1 min-w-0">
                    <p className="text-muted-foreground break-words">{step.instruction}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
